my_app/forum/routes.py
from my_app.forum.helper_functions import *
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_required
from my_app.forum.forms import ProposalForm
from my_app.models import User, Proposal, Character, Genre
from my_app.messaging.routes import check_if_unread


forum_bp = Blueprint('forum', __name__)


@forum_bp.route('/create_proposal', methods=['GET', 'POST'])
@login_required
def create_proposal():
    """Route to create a new proposal"""
    form = ProposalForm()
    if request.method == 'POST':
        form = modify_char_and_genre_entries(form)
        if request.form['button'] == 'Submit Proposal' and form.validate_on_submit():  # Form was completed & validated
            create_database_entries(form)
            flash('Your proposal has been created')
            return redirect(url_for('forum.view_my_proposals'))
    return render_template('proposal_form.html', form=form, unread_messages=check_if_unread())


@forum_bp.route('/display_proposals')
@login_required
def view_proposals():
    """Route to view all the proposals"""
    proposals = Proposal.query.all()
    genres = Genre.query.all()
    return render_template('proposals.html', proposals=proposals, genres=genres, unread_messages=check_if_unread())


@forum_bp.route('/display_proposals/<proposal_id>')
@login_required
def view_specific_proposal(proposal_id):
    """Route to view the information about a specific proposal"""
    proposal = Proposal.query.get(proposal_id)
    if proposal is None:  # If the proposal does not exist
        flash('The proposal the user is looking for does not exist')
        return redirect(url_for('forum.view_proposals'))

    # Get the info about the wanted proposal
    proposal_genres = Genre.query.filter_by(proposal_id=proposal_id)
    proposal_characters = Character.query.filter_by(proposal_id=proposal_id)
    proposal_user = User.query.get(proposal.user_id)
    return render_template('specific_proposal.html', proposal=proposal, genres=proposal_genres,
                           characters=proposal_characters, user=proposal_user, unread_messages=check_if_unread())


@forum_bp.route('/my_proposals')
@login_required
def view_my_proposals():
    """Route to view all the current user's proposals"""
    my_proposals = Proposal.query.filter_by(user_id=current_user.id).all()
    genres = Genre.query.all()
    return render_template('my_proposals.html', proposals=my_proposals, genres=genres,
                           unread_messages=check_if_unread())


@forum_bp.route('/edit_proposal/<proposal_id>', methods=['GET', 'POST'])
@login_required
def edit_proposal(proposal_id):
    """Route to edit (modify) an existing proposal"""
    # If the proposal that user wants to edit does not exist or was created by a different user
    if Proposal.query.get(proposal_id) is None or Proposal.query.get(proposal_id).user_id != current_user.id:
        flash('The proposal that the user is trying to edit does not exist/was not posted by the current user.')
        return redirect(url_for('forum.view_my_proposals'))

    proposal, characters, genres = extract_proposal_info(proposal_id)
    form = pre_populate_proposal_form(proposal, characters, genres)
    if request.method == 'POST':
        modify_char_and_genre_entries(form)
        if request.form['button'] == 'Submit Proposal' and form.validate_on_submit():  # Form was completed & validated
            modify_and_commit_proposal(form, proposal, characters, genres)
            return redirect(url_for('forum.view_my_proposals'))

    return render_template('proposal_form.html', form=form, unread_messages=check_if_unread())

my_app/main/routes.py
from flask import Blueprint, render_template, redirect
from flask_login import current_user, login_required
from my_app.messaging.routes import check_if_unread


main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    """Home route, which provides information to the user about the functionality of the app."""
    if not current_user.is_anonymous:  # If the user has logged in
        name = current_user.first_name
        return render_template('main_page.html', unread_messages=check_if_unread(), user_name=name)
    else:
        return render_template('main_page.html')


@main_bp.route('/dash_app/')
@login_required
def dash_app():
    """Route used to redirect to the dash app."""
    return redirect('/dash_app/')

my_app/templates/authorization_page.html
{% extends 'layout.html' %}
{% set location = 'authorization' %}
{% block content %}
    {# Display the form validation errors #}
    {% if form.errors %}
        <div class="alert alert-warning" role="alert">
            {% for field, errors in form.errors.items() %}
                {{ form[field].label }}: {{ ', '.join(errors) }}
            {% endfor %}
        </div>
    {% endif %}
    {# Display the signup form #}
    <form method="POST" action="{{ url_for('auth.signup') }}">
        {{ form.csrf_token }}
        {{ form.first_name.label(class="form-label") }} {{ form.first_name(class="form-control") }} <br>
        {{ form.last_name.label(class="form-label") }} {{ form.last_name(class="form-control") }} <br>
        {{ form.email.label(class="form-label") }} {{ form.email(class="form-control") }} <br>
        {{ form.password.label(class="form-label") }} {{ form.password(class="form-control") }} <br>
        {{ form.password_repeat.label(class="form-label") }} {{ form.password_repeat(class="form-control") }} <br>
        <input type="submit" value="Sign up">
    </form>
    {# Link to login page (if the user has already has an account) #}
    <a class="link-primary" href="{{ url_for("auth.login") }}">Already have an account?</a>
{% endblock %}

my_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# Bootstrap CSS #}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <title>Title</title>
</head>
<body>
    <header class="container-fluid">
        <br>
        {% include 'navbar.html' %}  {# Include the defined navigation bar in the header #}
    </header>
    <main>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </main>
    <script src="{{ url_for('static', filename='js/boostrap.bundle.js')}}" defer></script>
</body>
</html>

my_app/templates/login.html
{% extends 'layout.html' %}
{% set location = 'authorization' %}
{% block content %}
    {# Display the form validation errors #}
    {% if form.errors %}
        <div class="alert alert-warning" role="alert">
            {% for field, errors in form.errors.items() %}
                {{ form[field].label }}: {{ ', '.join(errors) }}
            {% endfor %}
        </div>
    {% endif %}
    {# Display any flashed messages #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    {# Display Login Form #}
    <form method="POST" action="{{ url_for('auth.login') }}">
        {{ form.csrf_token }}
        {{ form.email.label(class="form-label") }} {{ form.email(class="form-control") }} <br>
        {{ form.password.label(class="form-label") }} {{ form.password(class="form-control") }} <br>
        {{ form.remember.label(class="form-label") }} {{ form.remember(class="form-check-label") }} <br>
        <input type="submit" value="Log in">
    </form>
    {# Link to go to  #}
    <a class="link-primary" href="{{ url_for('auth.signup') }}">New to FilmSys?</a>
{% endblock %}

my_app/templates/main_page.html
{% extends 'layout.html' %}
{% set location = 'home' %}
{% block content %}
    <br><br><br><br><br>
    <h1 class="text-center">{{ 'Hello ' + user_name + "," if user_name}} welcome to FilmApp</h1>
    <br>
    <h3 class="text-muted">An Application in which users can post their film <u>proposals</u>, view the latest film data
                           through a series of carefully crafted <u>charts</u> and <u>chat</u> with other users.</h3>
{% endblock %}

my_app/templates/my_proposals.html
{% extends 'layout.html' %}
{% set location = 'my_proposals' %}
{% block content %}
    {# If there are any flashed messages, display them #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    {% if not proposals %}
        <br><h4>You have submitted no proposals</h4>
    {% else %}
        {# Go through each user proposal #}
        {% for proposal in proposals %}
            <div class="container">
                <div class="row">
                    <div class="card bg-info text-white">
                        <div class="card-body">
                            <h5 class="card-title">{{ proposal.title }}</h5>
                            {# If the proposal plot has less than 400 characters, display the plot entirely #}
                            {% if proposal.plot|length < 400 %}
                                <p class="card-text">{{ proposal.plot }}</p>
                            {# If the proposal plot is longer than 400 characters, only display the first 400 #}
                            {% else %}
                                <p class="card-text">{{ proposal.plot[:400] + "..." }}</p>
                            {% endif %}
                            <p class="card-text">
                            {# Go through all the genres in the database #}
                            {% for genre in genres %}
                                {# Only show the genres of the specific proposal that is being displayed #}
                                {% if genre.proposal_id == proposal.id %}
                                    <span class="badge bg-primary">{{ genre.genre_name }}</span>
                                {% endif %}
                            {% endfor %}
                            </p>
                            {# Button to edit proposal #}
                            <a href="{{ url_for('forum.edit_proposal', proposal_id=proposal.id) }}" class="btn
                                                                                                           btn-primary">
                                Edit Proposal
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
    {% endif %}
    {# Buttom to create new proposal #}
    <h4>
        <a href="{{ url_for('forum.create_proposal') }}" class="btn btn-primary align-content-center">
            Create New Proposal
        </a>
    </h4>
{% endblock %}

my_app/templates/navbar.html
{# Macro that will create a navigation link. location_for_active is a variable that defines the user location at which
the link will be set as active. The variable location (passed when rendering the template) informs about the current
location of the user #}
{% macro create_link(location_for_active, link_url, link_name) %}
    <a class="nav-link {{ 'active' if location == location_for_active }}" href="{{ url_for(link_url) }}">
        {{ link_name }}
        {# If there are any unread messages, display a notification symbol (red dot) over the Messages link #}
        {% if unread_messages and link_name == "Messages" %}
            <span class="position-relative top-0 start-0 translate-middle badge border border-light rounded-circle
                         bg-danger p-2"><span class="visually-hidden">unread messages</span></span>
        {% endif %}
    </a>
{%- endmacro %}

{# Create the navigation bar #}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand">FilmApp</a>  {# Name of the app #}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {# Define the different navigation links #}
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                {{ create_link('home', 'main.index', 'Home') }}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for("main.dash_app") }}">Dashboard</a>
            </li>
            <li class="nav-item">
                {{ create_link('proposals', 'forum.view_proposals', 'Proposals') }}
            </li>
            <li class="nav-item">
                {{ create_link('my_proposals', 'forum.view_my_proposals', 'My Proposals') }}
            </li>
            <li class="nav-item">
                {{ create_link('messages', 'message.view_messages', 'Messages') }}
            </li>
            <li class="nav-item">
                {# If user is at home and has been authenticated #}
                {% if not current_user.is_anonymous %}
                    {# Logout link can never be active #}
                    <a class="nav-link" href="{{ url_for("auth.logout") }}">Logout</a>
                {% else %}
                    {{ create_link('authorization', 'auth.login', 'Authorization') }}
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

my_app/templates/proposal_form.html
{% extends 'layout.html' %}
{% set location = 'my_proposals' %}
{% block content %}
    {# Display the form validation errors #}
    {% if form.errors %}
        <div class="alert alert-warning" role="alert">
            {% for field, errors in form.errors.items() %}
                {{ form[field].label }}: {{ ', '.join(errors) }}
            {% endfor %}
        </div>
    {% endif %}
    <br>
    {# Button to go back to viewing all the current user's proposals #}
    <a href="{{ url_for('forum.view_my_proposals') }}" class="btn btn-primary"><- Go back</a>
    <br><br>
    {# Define proposal form #}
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ form.title.label(class="form-label") }} {{ form.title(class="form-control") }} <br>
        {{ form.plot.label(class="form-label") }} {{ form.plot(class="form-control") }} <br>
        <p class="form-label">CHARACTERS</p>
        {# Have a section in the form for each of the characters (name and description) #}
        {% for character in form.characters %}
            {{ character.label(class="form-label") }} {{ character(class="form-control") }}
        {% endfor %} <br>
        {# Buttons for adding/removing characters #}
        <input type="submit" class="btn-secondary" name="button" value="Add Character">
        <input type="submit" class="btn-secondary" name="button" value="Remove Character"><br><br>
        <p class="form-label">GENRES</p>
        {# Have a section in the form for each of the genres #}
        {% for genre in form.genres %}
            {{ genre.label(class="form-label") }} {{ genre(class="form-control") }}
        {% endfor %} <br>
        {# Buttons for adding/removing genres #}
        <input type="submit" class="btn-secondary" name="button" value="Add Genre">
        <input type="submit" class="btn-secondary" name="button" value="Remove Genre"><br><br>
        {# Button for submitting the proposal #}
        <input type="submit" name="button" value="Submit Proposal">
    </form>
{% endblock %}

my_app/templates/proposals.html
{% extends 'layout.html' %}
{% set location = 'proposals' %}
{% block content %}
    {# If there are any flashed messages, display them #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    {% if not proposals %}
        <br><h4>No proposals have been submitted</h4>
    {% endif %}
    {# Go through each proposal in the database #}
    {% for proposal in proposals %}
        <div class="container">
            <div class="row">
                {# If the proposal was uploaded by the current user, display it in a different color #}
                <div class="card {{ 'bg-info text-white' if proposal.user_id == current_user.id }}">
                    <div class="card-body">
                        {# Show (Posted By You) if the current user uploaded the proposal #}
                        <h5 class="card-title">{{ proposal.title }}
                                               {{' (Posted By You)' if proposal.user_id == current_user.id}}</h5>
                        {# If the proposal plot has less than 400 characters, display the plot entirely #}
                        {% if proposal.plot|length < 400 %}
                            <p class="card-text">{{ proposal.plot }}</p>
                        {# If the proposal plot is longer than 400 characters, only display the first 400 #}
                        {% else %}
                            <p class="card-text">{{ proposal.plot[:400] + "..." }}</p>
                        {% endif %}
                        <p class="card-text">
                        {# Display the genres of the proposal #}
                        {% for genre in genres %}
                          {% if genre.proposal_id == proposal.id %}
                              <span class="badge bg-primary">{{ genre.genre_name }}</span>
                          {% endif %}
                        {% endfor %}
                        </p>
                        {# Button to view the information of a specific proposal #}
                        <a href="{{ url_for('forum.view_specific_proposal', proposal_id=proposal.id) }}"
                           class="btn btn-primary">
                            View Proposal
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <br>
    {% endfor %}
{% endblock %}

my_app/templates/send_message.html
{% extends 'layout.html' %}
{% set location = 'messages' %}
{% block content %}
    <br>
    {# Button to go back to viewing all the current user's chats #}
    <a href="{{ url_for('message.view_messages') }}" class="btn btn-primary"><- Go back</a>
    <br><br>
    <h4>{{ recipient.first_name + " " + recipient.last_name + ": " + recipient.email }}</h4>
    {# Go through each of the messages inside a chat #}
    {% for message in messages %}
        <div class="container">
            <div class="row">
                {# If the message was sent by the user, color it light and place it towards the right side #}
                {% if message.user_sender_id == current_user.id %}
                    <div class="col"></div>
                    <div class="card text-dark bg-light mb-3 col-7">
                        <div class="card-body">
                            <p class="card-text">{{ message.text }}</p>
                        </div>
                    </div>
                {# If the message was sent by the other user, color it dark and place it towards the left side #}
                {% else %}
                    <div class="card text-white bg-dark mb-3 col-7">
                        <div class="card-body">
                            <p class="card-text">{{ message.text }}</p>
                        </div>
                    </div>
                    <div class="col"></div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    {# Include form to send a new message #}
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ form.text.label(class="form-label") }} {{ form.text(class="form-control") }} <br>
        <input type="submit" name="button" value="Send Message">
    </form>
{% endblock %}

my_app/templates/specific_proposal.html
{% extends 'layout.html' %}
{% set location = 'proposals' %}
{% block content %}
    <br>
    {# Button to go back to viewing all the proposals #}
    <a href="{{ url_for('forum.view_proposals') }}" class="btn btn-primary"><- Go back</a>
    <br><br>
    <h3 class="text-center">{{ proposal.title }}</h3>
    <h5><u>PROPOSAL PLOT</u></h5>
    <p>{{ proposal.plot }}</p>
    <h5><u>Characters</u></h5>
    {# Display the information about each character in the proposal #}
    {% for character in characters %}
        <p class="fw-bold fst-italic">{{ character['character_name'] }}:
            <span class="fw-normal fst-normal">{{ character['character_description'] }}</span>
        </p>
    {% endfor %}
    <h5><u>Proposal Genres</u></h5>
    {# Display each genre in the proposal #}
    {% for genre in genres %}
        <h5 class="badge bg-primary">{{ genre.genre_name }}</h5>
    {% endfor %}
    <br>
    <h5><u>Posted by</u></h5>
    {# Create a link that will allow users to open the chat with the proposal's poster #}
    <a class="link-info" href="{{ url_for('message.send_message', user_id=user.id) }}">
        {{ user.first_name + " " + user.last_name }}
    </a>
{% endblock %}

my_app/templates/view_messages.html
{% extends 'layout.html' %}
{% set location = 'messages' %}
{% block content %}
    {# If there are any flashed messages, display them #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    {# Form to find a specific user with whom the current user would like to chat #}
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ form.user.label(class="form-label") }} {{ form.user(class="form-control") }} <br>
        <input type="submit" name="button" value="Find User">
    </form>
    {% if no_messages %}
        <br><h4 class="text-center">You have no messages</h4>
    {% else %}
        {# Go through all the users, last messages and unreads (whether a chat has unread messages) of each user chat #}
        {% for user, message, unread in users_and_messages_and_unreads %}
            {# If the last message is not None (the chat contains at least one message) #}
            {% if message %}
                <div class="container">
                    <div class="row">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ user.first_name + " " + user.last_name + ": " + user.email }}
                                </h5>
                                <p class="card-text">{{ message.text }}
                                {# If the last message was unread, display a notification symbol #}
                                {% if unread %}
                                    <span class="position-relative top-0 start-0 translate-middle badge border
                                                 border-light rounded-circle bg-danger p-2">
                                        <span class="visually-hidden">unread messages</span>
                                    </span>
                                {% endif %}
                                </p>
                                {# Button to open a specific chat #}
                                <a href="{{ url_for('message.send_message', user_id=user.id) }}" class="btn
                                                                                                        btn-primary">
                                    View Chat
                                </a>
                          </div>
                        </div>
                    </div>
                </div>
                <br>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}